Backend: Vivado
Board: pynq-z2
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
KerasH5: saved_weights_no_relu_bias.h5
KerasJson: saved_model_no_relu_bias.json
OutputDir: lenet5-proj
ProjectName: lenet5
Stamp: ec8Ec9ab
XilinxPart: xc7vx485tffg1761-2
