KerasJson: example-keras-model-files/jetTagger_Conv2D_Small.json
KerasH5:   example-keras-model-files/jetTagger_Conv2D_Small.h5
OutputDir: test_conv2d_batch_norm
ProjectName: myproject
XilinxPart: xcku115-flvf1924-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
DefaultPrecision: ap_fixed<18,8> 
