KerasJson: example-keras-model-files/KERAS_3layer_ternary_small.json
KerasH5:   example-keras-model-files/KERAS_3layer_ternary_small_weights.h5
#InputData: example-keras-model-files/KERAS_3layer_ternary_small_input_features.dat
#OutputPredictions: example-keras-model-files/KERAS_3layer_ternary_small_predictions.dat
#TruthLabels: example-keras-model-files/KERAS_3layer_ternary_small_truth_labels.dat
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
#  LayerType:
#    Dense:
#      Strategy: Resource
