KerasJson: example-keras-model-files/KERAS_3layer_binary_smaller.json
KerasH5:   example-keras-model-files/KERAS_3layer_binary_smaller_weights.h5
#InputData: example-keras-model-files/KERAS_3layer_binary_input_features.dat
#OutputPredictions: example-keras-model-files/KERAS_3layer_binary_predictions.dat
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
